appearhere/bloom

- README.md
> Update Readme with open source badges

- .travis.yml
> Add code climate test coverage reporting

- styleguide/components/Navigation/Navigation.js
- styleguide/components/Scaffold/Scaffold.css
- styleguide/components/Scaffold/Scaffold.js
- styleguide/screens/Patterns/Accessibility/Accessibility.js
- styleguide/screens/Patterns/Patterns.js
- Add link component to style guide scaffolding
- Adds an overview of the importance of accessibility
- Adds some initial resources on accessbility
- Adds documentation of the screen readable component
> Add documentation for accessibility to the style guide

- index.html
- package.json
- styleguide/components/IconShowcase/IconShowcase.js
- styleguide/components/Specimen/Specimen.css
- styleguide/components/Specimen/Specimen.js
- styleguide/components/Swatch/Swatch.js
- styleguide/screens/Design/Typography.js
- styleguide/screens/Patterns/Accessibility/Accessibility.js
- styleguide/screens/Patterns/Buttons/Buttons.js
- yarn.lock
- Moves the specimen's name declaration from being the first attribute to it's own prop
- Adds an additional prop for passing in a code example, `code`, for the specimen component
Depends on #349
> Add syntax highlighting to specimen component

- styleguide/components/Navigation/Navigation.js
- styleguide/screens/Patterns/LeftRight/LeftRight.css
- styleguide/screens/Patterns/LeftRight/LeftRight.js
- styleguide/screens/Patterns/Patterns.js
Adds documentation for the `LeftRight` layout component. Depends on #351
> Add LeftRight documentation

- styleguide/components/IconShowcase/IconShowcase.css
- styleguide/components/IconShowcase/IconShowcase.js
- styleguide/screens/Design/Iconography.js
- styleguide/screens/Design/icons.js
- Updates IconShowcase component to be more generic
- Updates IconShowcase component to allow the more control over the icon size
- Adds SpaceTypeIcon documentation to the iconography page
> Add space type icon documentation to style guide

- styleguide/components/Navigation/Navigation.js
- styleguide/components/Scaffold/Scaffold.css
- styleguide/components/Scaffold/Scaffold.js
- styleguide/screens/Design/ResponsiveDesign.js
* Reorder design navigation
* Add missing note
* Fix list styling
> Add fixes to ResponsiveDesign page

- styleguide/components/CodeBlock/CodeBlock.css
- styleguide/components/Specimen/Specimen.css
- styleguide/screens/Design/Typography.css
> Set specimen code blocks overflow-x to auto

- components/Animate/Swap.js
- components/Form/Input/Input.js
- components/Form/Select/Select.js
- components/GridFader/GridFader.js
- components/GridFader/GridFader.test.js
- package.json
- yarn.lock
Use react-transition-group module in preparation for react upgrade.
> Replace react-addons-transition-group

- components/Navigation/TabBar/TabBar.css
- components/Navigation/TabBar/TabBar.js
- components/Navigation/TabBar/TabBar.story.js
Allow TabBar to be horizontally scrollable
* Double TabWidth
* Offset first tab active underline
> Add scrollable functionality to TabBar

- components/Cards/Cards.story.js
- components/Cards/DestinationListingCard/DestinationListingCard.js
- components/Map/MarkableMap.js
Add a callback to hook into the click on a marker.
> Add callback hooks to map

- components/DeviceFrame/VideoDeviceFrame.js
- components/Video/Video.js
Add check for browser apis to Video components exports to make them server side renderable.
> Enable video ssr

- components/Btn/Btn.css
- Make hollow default button darker
- Fix default subtle button underline color
> Update button colors

- packages/core/src/components/Form/Select/Select.css
Add mozilla vendor rule for select component
> AH-1888 firefox issue

- packages/core/src/components/Calendar/DayPicker/DayPicker.js
Column heading props weren't being passed through day picker so the days of the week weren't receiving the isClosed method.
> Pass column heading props through day picker

- packages/core/src/components/OptionCard/OptionCard.css
- packages/core/src/components/OptionCard/OptionCard.js
- packages/core/src/components/OptionCard/OptionCard.test.js
- packages/core/src/components/index.js
- packages/core/src/index.js
- packages/playground/.storybook/config.js
- packages/playground/stories/OptionCard.story.js
Added new OptionCard component and related stories
> LFR-1352 Adding new OptionCard component

- packages/core/src/components/CollapsibleRow/CollapsibleRow.css
- packages/core/src/components/CollapsibleRow/CollapsibleRow.js
- packages/core/src/components/CollapsibleRow/CollapsibleRow.test.js
- packages/core/src/components/index.js
- packages/core/src/index.js
- packages/playground/.storybook/config.js
- packages/playground/stories/CollapsibleRow.story.js
Created new CollapsibleRow component
> LFR-1487 Adding new CollapsibleRow component

- packages/core/src/components/CollapsibleRow/CollapsibleRow.js
- packages/playground/stories/CollapsibleRow.story.js
We need to be able to control the opened state of the CollapsibleRow component via props
> Adding opened prop to CollapsibleRow component

- packages/core/src/components/CollapsibleRow/CollapsibleRow.css
- packages/core/src/components/CollapsibleRow/CollapsibleRow.js
- Added onClick prop to CollapsibleRow
- Updating border colour when opened
> Adding onClick prop to CollapsibleRow and updating styles when opened

- packages/core/src/components/CollapsibleProgressSteps/CollapsibleProgressSteps.css
- packages/core/src/components/CollapsibleProgressSteps/CollapsibleProgressSteps.js
- packages/core/src/components/CollapsibleRow/CollapsibleRow.css
- packages/core/src/components/CollapsibleRow/CollapsibleRow.js
- packages/core/src/components/index.js
- packages/core/src/index.js
- packages/playground/.storybook/config.js
- packages/playground/stories/CollapsibleProgressSteps.story.js
- packages/playground/stories/CollapsibleRow.story.js
- Added new `CollapsibleProgressSteps` component which creates an array of `CollapsibleRow`
- Added `border`, `onClick` and `marginBottom` props to `CollapsibleRow`
> Adding new collapsible progress steps component

- package.json
- packages/core/package.json
- yarn.lock
We currently have 1,477 High security vulnerabilities!
We can fix all yarn security vulnerabilities using yarn [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/)
| js-yaml| |
| ------------- |:-------------:|
| Low      | 0 |
| Moderate      |27 |
|  Critial     | 0 |
|  High     |  9 |
| braces| |
| ------------- |:-------------:|
| Low      | 244 |
| Moderate      | 0 |
|  Critial     | 0 |
|  High     |  0 |
| cryptiles| |
| ------------- |:-------------:|
| Low      | 0 |
| Moderate      | 21 |
|  Critial     | 0 |
|  High     |  16 |
|deep-extend| |
| ------------- |:-------------:|
| Low      | 15 |
| Moderate      | 0 |
|  Critial     | 0 |
|  High     |  0 |
| hoek | |
| ------------- |:-------------:|
| Low      | 0 |
| Moderate      | 63 |
|  Critial …
> LFR-1572 Fix security vulnerabilities

- packages/core/src/components/Map/MarkableMap.js
Reference:
https://docs.mapbox.com/mapbox-gl-js/api/#animationoptions
> Add animateFitBounds prop to MarkableMap

- now.json
- package.json
We're now using https://zeit.co/ to create preview apps for Bloom!
> Adding review app deployment using Now

- packages/core/src/components/Cards/DistrictCard/DistrictCard.css
- packages/core/src/components/Cards/DistrictCard/DistrictCard.js
- packages/core/src/components/Cards/DistrictCard/DistrictCard.test.js
- packages/core/src/components/index.js
- packages/core/src/index.js
- packages/playground/stories/Cards.story.js
> LFR-1670: Add district card

- packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.css
https://appearhere.atlassian.net/browse/LFR-1712
Reduced font size for price in space listing card
> LFR-1712 Reduce price font size in space listing card

- packages/core/src/components/Cards/DistrictCard/DistrictCard.css
Title and subtitle on District card are overflowing
> LFR-1663 Truncate title and subtitle on DistrictCard

- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardDesktop.css
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardDesktop.js
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardDesktop.test.js
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardMobile.css
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardMobile.js
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardMobile.test.js
- packages/core/src/components/IconLink/IconLink.css
- packages/core/src/components/IconLink/IconLink.js
- packages/core/src/components/IconLink/IconLink.test.js
- packages/core/src/components/RemoveOrphans/RemoveOrphans.js
- packages/core/src/components/index.js
- packages/core/src/index.js
- packages/playground/.storybook/config.js
- packages/playground/stories/Cards.story.js
- packages/playground/stories/IconLink.story.js
Adding SuccessStoryCardMobile and SuccessStoryCard desktop
The reason there are two is because the designs are so different
Also added IconLink component
https://appearhere.atlassian.net/browse/LFR-1720
> LFR-1720 Adding SuccessStory card

- packages/core/src/components/Carousel/Carousel.css
- packages/core/src/components/MobileCarousel/MobileCarousel.css
- packages/core/src/components/index.js
- packages/core/src/index.js
- Fixed alignment of carousel items on mobile
- Removed overflow-y scroll on mobile carousel
- Set default letter spacing and font weight of carousel titles
> Fixing overflow and typography issues with carousel

- packages/core/src/components/Form/IconInput/IconInput.js
- packages/core/src/components/Icon/IconCore.css
- packages/core/src/components/Icon/iconHelper.js
- packages/playground/stories/IconInput.story.js
- Allows the customisation of the height and width dimensions of an icon in `Icon` and `IconInput`.
- Adds a default height and width of `1em`
> LFR-1718: Sizable dimensions for icons

- packages/core/src/components/Video/PlayBtn/PlayBtn.css
Update the size of the play button for smaller devices
> Updating play button styles for mobile and desktop

- packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.css
- packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.js
- packages/core/src/components/Cards/DistrictCard/DistrictCard.css
- packages/core/src/components/Cards/PictureCard/PictureCard.css
- packages/core/src/components/Cards/PictureCard/PictureCard.js
- packages/core/src/components/Cards/SpaceFeatureCard/SpaceFeatureCard.js
- packages/core/src/components/Cards/SpaceListingCard/SpaceListingCard.js
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardDesktop.css
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardMobile.css
- Space cards CSS updates (removed border radius, height of images in carousel, paddings etc)
- Hid information block (location, sq ft etc) when information prop is empty
- Reduced title size on district card
- Changed success story card subtitle to white
- updated PictureCard to use inline image and added transition hover animation
> Space card updates and other misc css updates

- packages/core/src/components/Cards/DistrictCard/DistrictCard.js
- packages/core/src/components/IconLink/IconLink.js
added rest props to district card and icon link components so we can use onClick on web
> Adding rest props to district card and icon link components

- packages/core/src/components/Cards/AnimatedPictureCard/AnimatedPictureCard.css
- packages/core/src/components/Cards/AnimatedPictureCard/AnimatedPictureCard.js
- packages/core/src/components/Cards/AnimatedPictureCard/AnimatedPictureCard.test.js
- packages/core/src/components/Cards/PictureCard/PictureCard.css
- packages/core/src/components/Cards/PictureCard/PictureCard.js
- packages/core/src/components/Cards/PlaceListingCard/PlaceListingCard.css
- packages/core/src/components/Cards/PlaceListingCard/PlaceListingCard.js
- packages/core/src/components/Cards/SpaceFeatureCard/SpaceFeatureCard.js
- packages/core/src/components/index.js
- packages/core/src/index.js
- packages/playground/stories/Cards.story.js
- Created AnimatedPictureCard component
- Revert changes on PictureCard, SpaceListingCard and PlaceListingCard components
> Creating AnimatedPictureCard component and rollback PictureCard changes

- packages/core/src/components/Cards/AnimatedPictureCard/AnimatedPictureCard.js
- packages/core/src/components/Cards/Card/Card.js
- packages/core/src/components/Cards/CondensedSpaceCard/CondensedSpaceCard.js
- packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.js
- packages/core/src/components/Cards/DistrictCard/DistrictCard.js
- packages/core/src/components/Cards/EditorialCard/EditorialCard.js
- packages/core/src/components/Cards/EditorialCard/EventCard.js
- packages/core/src/components/Cards/EditorialCard/GuideCard.js
- packages/core/src/components/Cards/EmptyListingCard/EmptyListingCard.js
- packages/core/src/components/Cards/PictureCard/PictureCard.js
- packages/core/src/components/Cards/PlaceListingCard/PlaceListingCard.js
- packages/core/src/components/Cards/SpaceFeatureCard/SpaceFeatureCard.js
- packages/core/src/components/Cards/SpaceListingCard/SpaceListingCard.js
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardDesktop.js
- packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardMobile.js
- packages/core/src/components/FittedImage/FittedImage.js
- packages/core/src/components/OptionCard/OptionCard.js
Adding flow types to all card components
> LFR-1915 Adding Flow types to Card components

- packages/core/flow-typed/npm/react-motion_vx.x.js
- packages/core/src/components/Animate/Circle.js
- packages/core/src/components/Animate/Counter.js
- packages/core/src/components/Animate/EdgeFade.js
- packages/core/src/components/Animate/GraphOrnament.js
- packages/core/src/components/Animate/Roll.js
- packages/core/src/components/Animate/SplitWordEntrance.js
- packages/core/src/components/Animate/Sunrise.js
- packages/core/src/components/Animate/Swap.js
- packages/core/src/components/Animate/Typewriter.js
Added flow for Animate components
> LFR-1916 Adding Flow types to Animate components

- packages/core/src/components/Markdown/Markdown.js
- Use flow
- Switch to functional component
- Add options for target blank links and escaped html
> CHORE Update the markdown component

- packages/core/flow-typed/npm/moment_v2.x.x.js
- packages/core/package.json
- packages/core/src/components/Calendar/CalendarItem/CalendarItem.js
- packages/core/src/components/Calendar/CalendarMonth/CalendarMonth.js
- packages/core/src/components/Calendar/DayPicker/DayPicker.js
- packages/core/src/components/Calendar/DayPicker/DayPickerItem.js
- packages/core/src/components/Calendar/DayRange/DayRange.js
- packages/core/src/components/Calendar/DayRangePicker/DayRangePicker.js
- packages/core/src/components/Calendar/getCalendarMonth/getCalendarMonth.js
- yarn.lock
Added flow types for Calendar components
> LFR-1917 Adding Flow types to Calendar components

- packages/core/src/components/Hero/Hero.js
- packages/core/src/components/Hero/SquareHero.js
- packages/core/src/components/Icon/iconHelper.js
- packages/core/src/components/IconLink/IconLink.js
- packages/core/src/components/Indicators/Indicator.js
- packages/core/src/components/Indicators/IndicatorGroup.js
- packages/core/src/components/LeftRight/LeftRight.js
- packages/core/src/components/Link/Link.js
- packages/core/src/components/Loader/Loader.js
- packages/core/src/components/Markdown/Markdown.js
- packages/core/src/components/Medallion/Medallion.js
- packages/core/src/components/MobileCarousel/MobileCarousel.js
- packages/core/src/components/Modal/ModalAnimator.js
- packages/core/src/components/Modal/Window.js
- packages/core/src/components/Modal/WithCross.js
- packages/core/src/components/Moment/Moment.js
- packages/core/src/components/Notification/Notification.js
- packages/core/src/components/Pagination/Pagination.js
- packages/core/src/components/Pagination/PaginationLink.js
- packages/core/src/components/Pagination/PaginationTrack.js
- packages/core/src/components/Pagination/getPaginationTrack.js
- packages/core/src/utils/propTypeValidations/image.js
Adding flow to more components
> LFR-1927 Adding flow types to components

- packages/core/src/components/Markdown/Markdown.js
- packages/core/src/components/Panel/Panel.js
- packages/core/src/components/PhotoGrid/RandomSix.js
- packages/core/src/components/ProgressSteps/ProgressSteps.js
- packages/core/src/components/ProgressSteps/Step.js
- packages/core/src/components/RemoveOrphans/RemoveOrphans.js
- packages/core/src/components/ScreenReadable/ScreenReadable.js
- packages/core/src/components/SignPost/SignPost.js
- packages/core/src/components/SocialLinks/SocialLinks.js
- packages/core/src/components/SpaceTypeIcon/SpaceTypeIcon.js
- packages/core/src/components/SpaceTypeIcon/icons.js
- packages/core/src/components/StepIcon/StepIcon.js
- packages/core/src/components/StickyNode/StickyNode.js
- packages/core/src/components/Tether/Tether.js
- packages/core/src/components/Tooltip/Tooltip.js
> LFR-1928 Adding flow types to components

- packages/core/src/components/Form/AutoComplete/Heading.js
- packages/core/src/components/Form/AutoComplete/Input.js
- packages/core/src/components/Form/AutoComplete/Suggestion.js
- packages/core/src/components/Form/Checkbox/Checkbox.js
- packages/core/src/components/Form/CheckboxGroup/CheckboxGroup.js
- packages/core/src/components/Form/FormComponents.js
- packages/core/src/components/Form/IconInput/IconInput.js
- packages/core/src/components/Form/Input/Input.js
- packages/core/src/components/Form/InputField/InputField.js
- packages/core/src/components/Form/InputRange/InputRange.js
- packages/core/src/components/Form/InputRange/InputRangeWithHistogram.js
- packages/core/src/components/Form/InputRange/transformStepValues.js
- packages/core/src/components/Form/Radio/Radio.js
- packages/core/src/components/Form/RadioGroup/RadioGroup.js
- packages/core/src/components/Form/Select/Option.js
- packages/core/src/components/Form/Select/Select.js
- packages/core/src/components/Form/Star/Star.js
- packages/core/src/components/Form/StarRating/StarRating.js
> LFR-1920 Adding flow types to Form components

- packages/playground/stories/Carousel.story.js
- packages/playground/stories/Map.story.js
- packages/playground/stories/MobileCarousel.story.js
- packages/playground/stories/Pagination.story.js
- packages/playground/stories/transformStepValues.js
We don't really need prop-types in storybook anyway and we're now using flow
> LFR-1921 Removing proptypes from storybook

- .travis.yml
- package.json
- yarn.lock
- Added a linting stage 
- Running linting stage in travis and Now
- Added pre-commit hook
> LFR-1924: Running flow when committing and in CI

- .github/workflows/main.yaml
- .travis.yml
- README.md
- package.json
- Adds an action to lint flow through Github Actions
- Removes the step from Travis CI
> [CHORE] Move Linting to GH Actions 

- packages/core/src/components/Cards/DistrictCard/DistrictCard.js
- packages/playground/stories/Cards.story.js
Allow district cards without subtitles
> Make district card subtitles optional

- packages/core/.lintstagedrc.yml
- packages/core/src/components/Carousel/Carousel.css
- packages/core/src/components/Carousel/Carousel.js
- packages/core/src/components/MobileCarousel/MobileCarousel.css
- packages/core/src/components/MobileCarousel/MobileCarousel.js
- packages/playground/stories/Carousel.story.js
- packages/playground/stories/MobileCarousel.story.js
Added prop to carousels so we can have different title variants
> Adding small title to carousels

- packages/core/src/components/MobileCarousel/MobileCarousel.css
- packages/playground/stories/MobileCarousel.story.js
With children of varying heights, allow the slides content to flex and fill the height available.
> Allow mobile carousel to flex

- packages/core/src/components/Form/IconInput/IconInput.js
- packages/core/src/components/Icon/iconHelper.js
- packages/playground/stories/IconInput.story.js
Allow passing down of the onClick function for the icon in the iconInput component.
Also makes the onClick for Icon actually work - it wasn't before for some reason.
> Add onIconClick to iconInput

- packages/core/src/components/Carousel/Carousel.css
- packages/core/src/components/Carousel/Carousel.js
- packages/playground/stories/Carousel.story.js
Added medium title to carousel
> Adding medium title to carousel

- packages/core/src/components/Modal/WithCross.js
The classNames were not passed on correctly, as they were no longer part of rest.
> LFR-2598 fix modal classNames issue

- packages/core/src/components/Cards/AnimatedPictureCard/AnimatedPictureCard.css
Changed gradient to before to ensure the gradient is appearing over the card.
> LFR-2712 card gradient not appearing

- packages/core/src/components/Chip/Chip.css
- packages/core/src/components/Chip/Chip.js
- packages/core/src/components/Chip/Chip.test.js
- packages/core/src/components/index.js
- packages/core/src/globals/typography.css
- packages/playground/.storybook/config.js
- packages/playground/stories/Chip.story.js
Co-authored-by: Janie Amero <43782388+jamero102@users.noreply.github.com>
> LFR-3192: Add Chip component for tags

- .circleci/config.yml
- lerna.json
- package.json
- packages/core/src/components/Icon/iconHelper.js
- yarn.lock
Adds a CircleCI pipeline that will publish a new beta version everytime a commit is pushed to master, unless it is by AH Otto (when pushing the version).
> Add CircleCI pipeline to test & publish

- lerna.json
- packages/core/package.json
- packages/core/src/components/Calendar/DayPicker/DayPickerItem.css
- packages/playground/package.json
Update DatePickerItem styling to have a strikethrough for unavailable and disabled dates
> Add strikethrough to unavailable date in calendar
