appearhere/bloom

styleguide/screens/Patterns/Buttons/Buttons.css
styleguide/screens/Patterns/Buttons/Buttons.js
styleguide/shared.css

- Suggest we break content up to make it more readable, and easier to digest.
- Also increased spacing between each component

Add H3 titles to button documentation

---

styleguide/Styleguide.js
styleguide/components/ScrollToTop/ScrollToTop.js

Makes the style guide reset the scroll position to the top of the window when the application's location is updated

Add scroll reset on router transition

---

styleguide/components/Specimen/Specimen.css
styleguide/components/Specimen/Specimen.js

On smaller screens, when the code sample's line is too long, the text overflows the container and causes the page to scroll. This forces scroll on the container itself, so the text is contained within it, and the user can scroll each code sample individually.

Fix style guide's specimen component code sample overflowing on small screens

---

components/Form/Input/Input.test.js
styleguide/components/Navigation/Navigation.js
styleguide/screens/Patterns/Inputs/Inputs.js
styleguide/screens/Patterns/Inputs/Inputs.test.js
styleguide/screens/Patterns/Patterns.js

Adds documentation for form inputs to the Bloom style guide
- Refactor 'forms' documentation to 'inputs'

Add form input documentation to style guide

---

globals/z-index.css
styleguide/components/OffCanvasPanel/OffCanvasPanel.css

Prevent the style guide's off screen navigation overlay from sitting below the specimen component.

Fix specimen component z-index issue

---

styleguide/screens/Patterns/Tabs/Tabs.js

* Correct title.
* Add space before link to TabBar documentation.

Fix Tabs documentation page

---

package.json
server/server.js
styleguide/screens/Overview/introduction.md

Temporarily removes storybook from Bloom, while I figure out how to upgrade it to `^3.x.x`. See https://github.com/storybooks/storybook/issues/2122 for more information

Disable storybook and prevent access in production

---

components/Calendar/DayPicker/DayPickerItem.test.js
components/Dropdown/Dropdown.js
components/Form/InputField/InputField.test.js
components/Form/Select/Select.test.js
components/FunnelInputField/FunnelInputField.test.js
components/Icon/iconHelper.test.js
components/Modal/ModalAnimator.js
components/StickyNode/StickyNode.js
components/StickyNode/StickyNode.test.js
components/Tabs/Tab.test.js
components/Tether/Tether.js
components/Tether/test/Tether.test.js
components/Video/Scrubber/Scrubber.test.js
package.json
styleguide/components/OffCanvasPanel/OffCanvasPanel.js
styleguide/screens/Patterns/Dropdown/Dropdown.js
yarn.lock

* Remove [react-addons-test-utils](https://www.npmjs.com/package/react-addons-test-utils)
* Upgrade [react-portal](https://github.com/tajo/react-portal)
* Use stateless portal in `<Tether />` and `<Modal />`
* Rewrite `<Modal />` to return active as portal no longer accepts
active prop
* Remove unsupported portal props from `<Dropdown />`
* Remove unsupported portal props from `<OffCanvasPanel />`
* Upgrade [react-hot-loader](https://github.com/gaearon/react-hot-loader) to stable version
* Upgrade [@appearhere/react-stickynode](https://github.com/appearhere/react-stickynode)
* Install [raf](https://github.com/chrisdickinson/raf) poylfill for jest

Upgrade to React 16

---

components/AreaUnits/AreaUnits.js

The `<sup />` tag creates issues with the line height of the parent element, `&sup2;` leverages the symbol shipped with the font.

Use proper symbol for square meters

---

config/webpack.config.dev.js
config/webpack.config.prod.js
index.html
package.json
styleguide/Styleguide.js
styleguide/utils/GoogleAnalytics.js
yarn.lock

`react-ga` is unneeded dependency which causes issues when exporting bloom library for react 16. We can use gtag default script to track pageviews.

Move analytics to gtag without react-ga

---

components/Cards/PictureCard/PictureCard.css

The opacity transition of the picture card is making the embedded svg glitchy. Adding `will-change: opacity` should make it more stable.

Fix card animation glitch on Chrome and Opera

---

packages/core/src/components/Calendar/DayPicker/DayPicker.js

Our specific use case was to add a FullStory "magic class" to the
component's header.

Users can pass classNames to DayPicker

---

packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.js

This component is only being used as part of the `SpaceListingCard` which is used to display the space listing cards within the search results. 
This PR changes the target attribute within links in this component so as to open in a new tab instead of redirecting the user.

PG-1849 Open links in DestinationListingCard in new tab

---

packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.css
packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.js
packages/playground/stories/Cards.story.js

This PR makes two changes to the DestinationListingCard component: 
1) Moving the positioning of the `badge` prop. The previous positioning does not have any use case anymore and we seem to be positioning badges in a different fixed place in current designs. 
2) Creating a Special variant for the DestinationListingCard - the difference between this and the default variant is that the colour of the additional information font is gold.

Modify DestinationListingCard

---

packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.css

The changes in the last version update to the DestinationListingCard affected the display width of the `additionalInformationText` content where it was cutting it off. 
This fixes that by setting a flex value.

Fix DestinationListingCard text width

---

packages/core/src/components/CollapsibleRow/CollapsibleRow.css

Updated left content in collapsible panel to use content-box instead of border-box

Fixing left content sizing bug with collapsible panel

---

packages/core/src/components/CollapsibleProgressSteps/CollapsibleProgressSteps.css
packages/core/src/components/CollapsibleProgressSteps/CollapsibleProgressSteps.js
packages/core/src/components/CollapsibleRow/CollapsibleRow.js

* Remove unneccesary additional markup and replace with css.
* Add `box-sizing: border-box` to fix issue when using in other projects where
box-sizing is set globally.

CHORE: Simplify progress steps

---

packages/core/src/components/Calendar/CalendarItem/CalendarItem.css
packages/core/src/components/Calendar/CalendarItem/CalendarItem.js
packages/core/src/components/Calendar/CalendarItem/CalendarItem.test.js
packages/core/src/components/Calendar/DayPicker/DayPickerItem.js

We needed to display the prices for each day on the bloom calendar. To make this as reusable as possible, I called it subtext, as the text is greyed out and below the main day text.

PG-2105 add subtext to calendaritem

---

packages/core/src/components/Calendar/CalendarItem/CalendarItem.css

When the subtext given to the calendar was too big, it was becoming offcenter. This padding fix removes that issue.

PG-2015 fix calendar day padding

---

packages/core/package.json
packages/core/src/components/ScreenSize/ScreenSize.js
packages/core/src/components/ScreenSize/ScreenSize.test.js
packages/core/src/components/index.js
packages/core/src/index.js
yarn.lock

We Currently have a `withMobile` higher order component on the web project but I think this should be moved to Bloom.
I've created a `ScreenSize` render prop component using hooks which stores if the user is on mobile, tablet or desktop

Adding new ScreenSize component

---

packages/core/package.json
packages/core/rollup.config.js
packages/core/src/components/Map/MarkableMap.js
packages/core/src/utils/mapboxgl/mapboxgl.js
yarn.lock

We were maintaining [our own fork](https://github.com/appearhere/mapbox-gl-js) of the [mapbox-gl](https://github.com/mapbox/mapbox-gl-js) library. And our fork had not been updated for 2-3 years, so it's getting a bit dangerous to keep it.
On the other hand, we also needed [this bugfix](https://github.com/mapbox/mapbox-gl-js/pull/9021/files) because mapbox started causing too many `UserAborted` errors, and our Sentry account suddenly started going over-quota.
By using the real library we can take advantage of updates when they come out, and without having to maintain another repository for no apparent reason.
Please mention anything you might see as problematic functionality-wise.
2 methods we're using from Mapbox's library:
- https://docs.mapbox.com/mapbox-gl-js/api/#geojsonsource#getclus …

PG-2161 Use Mapbox's mapbox-gl instead of our forked version

---

packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.js

We now use the original nuka carousel prop called afterSlide, which gives us the same arguments and fixes a problem where on clicking to load a next or previous image just did not trigger the callback, and therefore the image did not load.
Ticket: https://appearhere.atlassian.net/browse/PG-2283

Fix left-over onChange from nuka-carousel fork

---

packages/core/src/components/Cards/DistrictCard/DistrictCard.css

Update the district card component with the following:
- Image is now using `object-fit`
- Use a smaller fontsize for supporting copy

Update District card to have object-fit and use smaller font

---

packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardMobile.css
packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardMobile.js

The desktop success story cards take a `variant`  prop which was missing on the mobile version

Adding variant to success story mobile card

---

packages/core/src/components/Form/Star/Star.js
packages/playground/package.json
packages/playground/stories/Animate.story.js
packages/playground/stories/Carousel.story.js
packages/playground/stories/CollapsibleRow.story.js
packages/playground/stories/MobileCarousel.story.js
packages/playground/stories/PhotoGrid.story.js
packages/playground/stories/RadioGroup.story.js
packages/playground/stories/Star.story.js
yarn.lock

We had a few errors and warnings in Storybook that are easily fixable.
The ticket states:
- HTTP requests to placekitten
- 403 from fast.fonts (which is now returning 200 OK without any changes)
- SameSite on cookie from Unsplash, but this is something that only Unsplash can fix and nothing to do on our end, unless we want to look for a random image provider that has handled this
To see what errors&warnings this PR fixes, look at the commit messages.
Ticket: https://appearhere.atlassian.net/browse/PG-2359

Fix console errors

---

packages/core/src/components/Calendar/DayPicker/DayPicker.css
packages/core/src/components/Calendar/DayPicker/DayPicker.js
packages/playground/stories/DayPicker.story.js

Passing a `maskSize` to a daypicker will now show a number of
months equal to the `maskSize`.

Feature: display multiple months in daypicker

---

packages/core/src/components/Cards/SuccessStoryCard/SuccessStoryCardDesktop.js

The link text for the success story desktop card is hardcoded. Updated to use props instead

Adding linkText to SuccessStoryCardDesktop

---

packages/core/src/components/Cards/DestinationListingCard/DestinationListingCard.js

We've faced issues with Carousel when users would click on the Carousel to get the next image the callback would be called after the Carousel has finished the transition from one image to another rather than before the transition finishes.
This is a problem because we're lazy-loading the images `onCarouselChange` and there's ~0.5 second delay in between when the user clicks to see the next image in the carousel and when we actually load it.
This solves the problem by calling the `onCarouselChange` before the slide transition completes and giving us more time to load the image and make the lazy-load smoother.
Note: this is a breaking change as the `beforeSlide` calls the callback with different parameters than `afterSlide`.
The current behaviour passes an index of the nextImage (the one …

[PG-2654] 🚀 Run `onCarouselChange` callback `beforeSlide` not after

---

packages/core/src/components/Cards/DistrictCard/DistrictCard.css
packages/core/src/components/Cards/DistrictCard/DistrictCard.js
packages/playground/stories/Cards.story.js

By default we truncate the text on the title and subtitle, we want to be able to turn off this default behaviour via a prop.

Optionally truncate text for district card

---

packages/core/src/components/DismissablePanel/DismissablePanel.css

- The cross icon was appearing below the content, it should be pulled to
the right

PG-2749 Fix the dismissable panel style

---

packages/core/src/components/Panel/Panel.js

- Some styles passed into the child `Panel` component via the
`className` prop from the parent `DismissablePanel` were getting
overwritten by the root styles for the `Panel`.
- This meant that `DismissablePanel` was not displaying the correct way
due to `display` style getting overwritten.
- This commit ensures that styles passed in via `className` take precedence

PG-2749 Ensure parent styles are used for Panel.js

---

packages/core/src/components/DismissablePanel/DismissablePanel.css
packages/core/src/components/Panel/Panel.js

- `DismissablePanel` styles were getting overwritten by the `Panel`
child component's styles. This commit increases the specificity of
the `DismissablePanel` root css to make sure it takes precedence.

PG-2749 Increase specificty of DismissablePanel styles

---

packages/core/src/components/Form/IconInput/IconInput.js
packages/core/src/components/Icon/iconHelper.js
packages/playground/stories/IconInput.story.js

This reverts commit ef7a42c, reversing changes made to 590d898.
We shouldn't add a click event to an icon within an input as it causes accessibility issues, if we want to be able to click the icon, we should render a button next to the input which ican be focused, tabbed etc.

Add focus to IconInput

---

packages/core/src/components/Calendar/DayPicker/DayPickerItem.css
packages/core/src/components/Calendar/DayPicker/DayPickerItem.js

In order for us to differentiate between 100% available, 100% unavailabe, underoffer and unknown availability, we have added three further colours for the daypicker.

PG-2971 add coloured days on daypicker

---

.github/CODEOWNERS

This will help notify us on automated PRs created by `dependabot`.
Most of the file is commented for now, except https://github.com/appearhere/bloom/compare/chore/add-code-owners?expand=1#diff-5cfb934ca0ec4c1743905a51dc428b84R3 which sets a rule to notify the entire `@developers` group
Read more about code owners here:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

[CHORE] Add CODEOWNERS

---

package.json
yarn.lock

- Versions below 0.2.1 have a security vulnerability
https://snyk.io/vuln/SNYK-JS-MINIMIST-559764
- Resolve minimist to 0.2.1 to fix the vulnerability

PG-3060 Fix minimist security vulnerability

---

packages/playground/package.json

Since using a custom domain for gihub pages, we need to have a cname file as part of the deployment.

CHORE: Add cname file during deployment

---

packages/core/src/components/Modal/WithCross.js

In order to add some customisation of the placement of the cross of the WithCross modal, the classNames property was added

LFR-2598 add classnames to withCross modal component

---

packages/core/src/components/Badge/Badge.css
packages/core/src/components/Badge/Badge.js
packages/playground/stories/Badge.story.js

Adds the icon prop to the badge component so you can pass down an icon name.

Add icon to badge component

---

packages/core/src/components/Icon/icons/icon-cross.svg

When displaying the dismissable panel with a cross, update the
icon colour to match the font colour

Fix the icon cross colour

---

packages/core/src/components/Tabs/Tabs.js
packages/playground/stories/Tabs.story.js

* When rendering tabs, we loop through the children, we should ignore null children.
* Preserve the child callback props for the tabs
* Allow defining an initially selected tab other than the first

Improve tabs

---

packages/core/src/components/Icon/iconHelper.js

Clicking on the icon of an icon input should focus the input. The
onClcik was not firing.

CHORE: fix icon input bug
